#include "EphemeralLevelListLayer.hpp"

#include <Geode/utils/cocos.hpp>
#include <Geode/cocos/CCDirector.h>
#include <Geode/binding/GJGameLevel.hpp>
#include <Geode/binding/GJListLayer.hpp>
#include <Geode/binding/CustomListView.hpp>
#include <Geode/binding/TableView.hpp>
#include <Geode/binding/GameStatsManager.hpp>
#include <Geode/binding/LocalLevelManager.hpp>
#include <Geode/binding/GJLevelList.hpp>
#include <Geode/binding/LevelListLayer.hpp>
#include <Geode/utils/base64.hpp>
#include <Geode/ui/Scrollbar.hpp>
#include <Geode/ui/General.hpp>
#include <Geode/loader/Mod.hpp>

namespace horn {

bool EphemeralLevelListLayer::init(cocos2d::CCArray* levels, const std::string& name, cocos2d::ccColor3B barColor) {
    if (!cocos2d::CCLayer::init()) {
        return false;
    }
    auto windowSize = cocos2d::CCDirector::get()->getWinSize();
    m_barColor = barColor;
    m_levels = levels;
    CC_SAFE_RETAIN(m_levels);

    auto* background = geode::createLayerBG();
    addChild(background, -2);

    auto* corner1 = cocos2d::CCSprite::createWithSpriteFrameName("GJ_sideArt_001.png");
    corner1->setAnchorPoint({ 0.0f, 0.0f });
    corner1->setPosition({ -1.0f, -1.0f });
    corner1->setID("left-corner");
    addChild(corner1);

    auto* corner2 = cocos2d::CCSprite::createWithSpriteFrameName("GJ_sideArt_001.png");
    corner2->setFlipX(true);
    corner2->setAnchorPoint({ 1.0f, 0.0f });
    corner2->setPosition({ windowSize.width + 1.0f, -1.0f });
    corner2->setID("right-corner");
    addChild(corner2);

    auto* backButton = CCMenuItemSpriteExtra::create(
        cocos2d::CCSprite::createWithSpriteFrameName("GJ_arrow_01_001.png"),
        this,
        menu_selector(EphemeralLevelListLayer::onClickBack)
    );
    backButton->setSizeMult(1.2f);
    backButton->setID("back-button");
    backButton->setPosition(20.0f, 20.0f);

    auto* backMenu = cocos2d::CCMenu::create();
    backMenu->ignoreAnchorPointForPosition(false);
    backMenu->setContentSize({ 40.0f, 40.0f });
    backMenu->setAnchorPoint({ 0.0f, 1.0f });
    backMenu->setPosition(4.0f, windowSize.height - 3.0f);
    backMenu->addChild(backButton);
    addChild(backMenu);

    setKeypadEnabled(true);

    if (m_levels->count() <= 100) {
        auto* copySprite = cocos2d::CCSprite::createWithSpriteFrameName("GJ_duplicateBtn_001.png");
        copySprite->setScale(0.8f);
        auto* copyButton = CCMenuItemSpriteExtra::create(
            copySprite,
            this,
            menu_selector(EphemeralLevelListLayer::onClickCopy)
        );
        copyButton->setSizeMult(1.2f);
        copyButton->setID("copy-button");
        copyButton->setPosition(20.0f, 20.0f);

        auto* copyMenu = cocos2d::CCMenu::create();
        copyMenu->ignoreAnchorPointForPosition(false);
        copyMenu->setContentSize({ 40.0f, 40.0f });
        copyMenu->setAnchorPoint({ 1.0f, 1.0f });
        copyMenu->setPosition(windowSize.width - 6.0f, windowSize.height - 6.0f);
        copyMenu->addChild(copyButton);
        addChild(copyMenu);
    }

    m_name = name;
    auto* title = cocos2d::CCLabelBMFont::create(m_name.c_str(), "bigFont.fnt");
    title->limitLabelWidth(360.0f, 0.8f, 0.4f);
    title->setPosition(windowSize.width / 2.0f, windowSize.height / 2.0f + 140.0f);
    title->setID("title-label");
    addChild(title);

    return true;
}

EphemeralLevelListLayer::~EphemeralLevelListLayer() {
    CC_SAFE_RELEASE(m_levels);
}

void EphemeralLevelListLayer::onClickBack(cocos2d::CCObject* sender) {
    keyBackClicked();
}

void EphemeralLevelListLayer::keyBackClicked() {
    cocos2d::CCDirector::get()->popSceneWithTransition(0.5f, cocos2d::PopTransition::kPopTransitionFade);
}

void EphemeralLevelListLayer::onClickCopy(cocos2d::CCObject* sender) {
    auto* localLevels = LocalLevelManager::get();
    auto* levelList = GJLevelList::create();
    levelList->m_listType = GJLevelType::Editor;
    levelList->m_listName = m_name;
    levelList->m_listDesc = geode::utils::base64::encode("Generated by Underrated Non-Demons (Geode mod)");
    for (auto* level : geode::cocos::CCArrayExt<GJGameLevel*>(m_levels)) {
        levelList->addLevelToList(level);
    }
    localLevels->m_localLists->insertObject(levelList, 0);
    auto* scene = LevelListLayer::scene(levelList);
    cocos2d::CCDirector::get()->pushScene(cocos2d::CCTransitionFade::create(0.5, scene));
}

void EphemeralLevelListLayer::onEnter() {
    cocos2d::CCLayer::onEnter();
    auto windowSize = cocos2d::CCDirector::get()->getWinSize();
    if (m_refreshingContent) {
        m_refreshingContent->removeFromParent();
    }
    m_refreshingContent = cocos2d::CCNode::create();
    m_refreshingContent->setAnchorPoint({ 0.0f, 0.0f });
    m_refreshingContent->setContentSize({ 0.0f, 0.0f });
    m_refreshingContent->setPosition(0.0f, 0.0f);
    addChild(m_refreshingContent);

    // calculate number of levels completed
    int levelsCompleted = 0;
    int levelsTotal = m_levels->count();
    auto* stats = GameStatsManager::sharedState();
    for (auto* level : geode::cocos::CCArrayExt<GJGameLevel*>(m_levels)) {
        levelsCompleted += stats->hasCompletedOnlineLevel(level->m_levelID);
    }

    // list view like LevelListLayer
    // the scroll height resuming thing seems to be done automatically most of the time, so I'm not going to mess with it
    auto* listView = CustomListView::create(m_levels, BoomListType::Level3, 220.0f, 356.0f);
    auto* listLayer = GJListLayer::create(listView, "", { 191, 114, 62, 255 }, 356.0f, 220.0f, 1);
    listLayer->ignoreAnchorPointForPosition(false);
    listLayer->setPosition(windowSize.width / 2.0f, windowSize.height / 2.0f - 5.0f);
    listLayer->setID("level-list"_spr);
    m_refreshingContent->addChild(listLayer);

    // the scrollbar is unnecessary when there's less than 5, and buggy when there's exactly 5???
    if (levelsTotal > 5) {
        auto* scrollBar = geode::Scrollbar::create(static_cast<CCScrollLayerExt*>(listView->m_tableView));
        scrollBar->setAnchorPoint({ 0.0f, 0.5f });
        scrollBar->setPosition(windowSize.width / 2.0f + 193.5f, windowSize.height / 2.0f - 5.0f);
        scrollBar->setID("scrollbar"_spr);
        m_refreshingContent->addChild(scrollBar);
    }

    // progress bar
    auto* progressBarBG = cocos2d::CCSprite::create("GJ_progressBar_001.png");
    progressBarBG->setColor({ 0, 0, 0 });
    progressBarBG->setOpacity(125);
    progressBarBG->setScale(0.8f);
    progressBarBG->setContentSize({ 340.0f, 20.0f });
    progressBarBG->setPosition({ windowSize.width / 2.0f, windowSize.height / 2.0f - 144.0f });
    progressBarBG->setID("progress-bar");
    m_refreshingContent->addChild(progressBarBG, 3);

    if (levelsCompleted) {
        float progressWidth = 340.0f * levelsCompleted / levelsTotal;
        auto* progressBar = cocos2d::CCSprite::create("GJ_progressBar_001.png");
        progressBar->setColor(m_barColor);
        progressBar->setScaleX(0.98);
        progressBar->setScaleY(0.76);
        progressBar->setTextureRect({ 0.0f, 0.0f, progressWidth, 20.0f });
        progressBar->setContentSize({ progressWidth, 20.0f });
        progressBar->setAnchorPoint({ 0.0f, 0.5f });
        progressBar->setPosition({ 3.4f, 10.0f });
        progressBarBG->addChild(progressBar);
    }

    std::string completedText = fmt::format("{}/{} ({}%)", levelsCompleted, levelsTotal, levelsCompleted * 100 / levelsTotal);
    auto* completedSprite = cocos2d::CCLabelBMFont::create(completedText.c_str(), "bigFont.fnt");
    completedSprite->setScale(0.5f);
    completedSprite->setPosition(windowSize.width / 2.0f, windowSize.height / 2.0f - 143.0f);
    completedSprite->setID("progress-bar-label");
    m_refreshingContent->addChild(completedSprite, 4);
}

void EphemeralLevelListLayer::onExit() {
    if (m_refreshingContent) {
        m_refreshingContent->removeFromParent();
        m_refreshingContent = nullptr;
    }
    cocos2d::CCLayer::onExit();
}

}
